version: '3.9'

networks:
  traefik_proxy:
    external: true
    
services:
  pocketjam-leaderboard:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    env_file:
      - .env
    networks:
      - traefik_proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.secret-api.rule=Host(`pocketjam.radhamante.fr`)"
      - "traefik.http.routers.secret-api.entrypoints=websecure"
      - "traefik.http.routers.secret-api.tls=true"
      - "traefik.http.routers.secret-api.tls.certresolver=myresolver"
      - "traefik.http.services.secret-api.loadbalancer.server.port=8000"
    

volumes:
  pg_data:
